# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180317_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssss', to='app01.Classes'),
        ),
    ]
